export const quoteList = [
  "The supreme art of war is to subdue the enemy without fighting.",
  "She looked as though butter wouldn't melt in her mouth ... or anywhere else.",
  "Comparison is the thief of joy.",
  "Care about what other people think, and you will always be their prisoner.",
  "Hey, I know! I'll use my trusty frying pan as a drying pan!",
  "Ravioli Ravioli Sableyeioli",
  "I love jelly donuts.",
  "Fear leads to anger, anger leads to hate, and hate leads to being a gangster.",
  "Sir, this is a Wendys.",
  "I am the Prince of Wales, and think not, Percy, to share with me in glory anymore: Two stars keep not their motion in one sphere.",
  "Work, work",
  "You're not as safe in Wisconsin as you think you are.",
  "It's hard to know they're still out there, it's hard to know that you still care.",
  "You really pulled a Charlie Gordon.",
  "Hold the brake and gas and see which gives out first.",
  "It is impossible to lie in the mud and not have it cling to you when at last you rise.",
  "When you wish to kill a wolf, you do not go stumbling through the forest after it. You set out meat and wait for the scent of it to drive the wolf beyond caution.",
  "Intuition is firmly substantiated.",
  "Theology, sir, is a fortress; no crack in a fortress may be accounted small.",
  `Hail Mary, full of grace.
  The lord is with thee.`,
  "The line dividing good and evil cuts through the heart of every human being. And who is willing to destroy a piece of their own heart?",
  "I need to bring this ham in because we're running low on ham in the theatre.",
  "How quick the turn from blessed to cursed.",
  "Base stats of a flower.",
  "A lifetime isn't nearly long enough to figure it out.",
  "Sticker",
];
